### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by goku-1993** [PodgroupConnectivity/kiopcgenerator#4]
Dear Community,

When running the kiopc generator I am getting the following error. Please let me know what is the issue. 

------------------
Traceback (most recent call last):
  File "/home/ubu18_oai/.local/bin/kiopcgen", line 14, in <module>
    import kiopcgenerator
  File "/home/ubu18_oai/.local/lib/python2.7/site-packages/kiopcgenerator/__init__.py", line 9, in <module>
    from .lib import *
  File "/home/ubu18_oai/.local/lib/python2.7/site-packages/kiopcgenerator/lib.py", line 42
    print(f'[DBG]calc_opc_hex: op({len(op)}) KI({len(ki)}) IV({len(iv)})')
                                                                        ^
SyntaxError: invalid syntax
------------------------

Any help from you would be deeply appreciated. Please provide your insights.

WR,
Gokul

**Comment by fontanon** [comment]
Please use python3 @goku-1993

**Comment by fontanon** [comment]
Would you @Lisaapadhi or @goku-1993 confirm it worked for you with python3 ?

**Comment by Lisaapadhi** [comment]
Yes worked with python 3. Thanks

**Comment by goku-1993** [comment]
Hi,
yes. it did. If possible please change it in the read file too.
Thank you.
Gokul
