### ISSUE TITLE
syntax error while trying to run the Kiopcgenerator using python

### ISSUE THREAD

**Issue by Lisaapadhi** [PodgroupConnectivity/kiopcgenerator#5]
File "Python/2.7/lib/python/site-packages/kiopcgenerator/lib.py", line 42
    print(f'[DBG]calc_opc_hex: op({len(op)}) KI({len(ki)}) IV({len(iv)})')
                                                                        ^
SyntaxError: invalid syntax

**Comment by fontanon** [comment]
Please use Python3.x @Lisaapadhi

**Comment by fontanon** [comment]
Duplicates #4

**Comment by Lisaapadhi** [comment]
Yes, working amazing with Python 3.x
