### ISSUE TITLE
kiopcgen not working

### ISSUE THREAD

**Issue by yiyangwei** [PodgroupConnectivity/kiopcgenerator#7]
I followed every step in the instruction, but when I tried to run the program and got the following error. Could you kindly help resolve this issue?
nano@nano-EPC:~/kiopcgenerator$ kiopcgen  -o D7DECB1F50404CC29ECBF989FE73AFC5 -t 2257CC6E9746434B89F346F0276CCAEC
Traceback (most recent call last):
  File "/usr/local/bin/kiopcgen", line 4, in <module>
    __import__('pkg_resources').run_script('kiopcgenerator==0.1.4', 'kiopcgen')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1429, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/kiopcgen' not found in metadata at '/home/nano/.local/lib/python2.7/site-packages/kiopcgenerator-0.1.4.egg-info'

**Comment by fontanon** [comment]
Please have a look at `README.md` only works with Python3.x

**Comment by yiyangwei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，你的邮件我已收到。
